'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Pencil, Plus, X } from 'lucide-react';
import { getToken } from '@/hooks/use-auth';
import type { PropertyPlan } from '@/lib/property';

type FormState={name:string;durationDays:string;listingFee:string;featuredDays:string;maxPhotos:string;active:boolean};
const empty:FormState={name:'',durationDays:'7',listingFee:'0',featuredDays:'0',maxPhotos:'20',active:true};

export default function PropertyPlanManager(){const [plans,setPlans]=useState<PropertyPlan[]>([]),[editing,setEditing]=useState<PropertyPlan|null|undefined>(undefined),[expanded,setExpanded]=useState(false),[form,setForm]=useState<FormState>(empty),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{const response=await fetch('/api/backend/property/admin/plans',{headers:{Authorization:`Bearer ${getToken()}`},cache:'no-store'});const body=await response.json().catch(()=>[]);if(!response.ok)throw new Error(body.message||'Unable to load posting plans');setPlans(body);},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load().catch(e=>setError(e.message)),0);return()=>window.clearTimeout(timer);},[load]);
 const open=(plan?:PropertyPlan)=>{setExpanded(true);setEditing(plan??null);setForm(plan?{name:plan.name,durationDays:String(plan.durationDays),listingFee:String(plan.listingFee),featuredDays:String(plan.featuredDays),maxPhotos:String(plan.maxPhotos),active:plan.active}:empty);setError('');};
 const closeForm=()=>{setEditing(undefined);setError('');};
 const closePanel=()=>{setExpanded(false);setEditing(undefined);setError('');};
 const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{const payload={name:form.name,durationDays:Number(form.durationDays),listingFee:Number(form.listingFee),featuredDays:Number(form.featuredDays),maxPhotos:Number(form.maxPhotos),active:form.active};const url=editing?`/api/backend/property/admin/plans/${editing.id}`:'/api/backend/property/admin/plans';const response=await fetch(url,{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${getToken()}`},body:JSON.stringify(payload)});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||'Unable to save posting plan');await load();closeForm();}catch(e){setError(e instanceof Error?e.message:'Unable to save posting plan');}finally{setSaving(false);}};
 return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">Property Posting Tier Plans</h2><p className="mt-1 text-sm text-slate-500">Control the posting cost, validity period, photo limit and featured exposure.</p></div><div className="flex items-center gap-2"><button onClick={()=>expanded?open():setExpanded(true)} className="flex items-center gap-2 rounded-xl bg-[#DB0002] px-4 py-3 text-sm font-black text-white"><Plus size={18}/>{expanded?'Create Tier Plan':'Show Tier Plans'}</button>{expanded&&<button type="button" onClick={closePanel} aria-label="Close tier plans" title="Close tier plans" className="flex size-11 items-center justify-center rounded-xl border text-slate-600 hover:bg-slate-50"><X size={20}/></button>}</div></div>
  {error&&editing===undefined&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}
  {expanded&&editing!==undefined&&<form onSubmit={submit} className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-5 shadow-sm"><div className="flex items-start justify-between"><div><h3 className="text-xl font-black">{editing?'Edit Posting Tier':'Create Posting Tier'}</h3><p className="mt-1 text-sm text-slate-500">Changes to duration and cost apply to future postings.</p></div><button type="button" onClick={closeForm} aria-label="Close form" className="rounded-lg p-2 text-slate-500 hover:bg-white"><X/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-bold sm:col-span-2">Plan name<input autoFocus required minLength={2} value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} placeholder="e.g. Standard 15 Days" className="mt-1 w-full rounded-xl border bg-white p-3 font-normal"/></label><label className="text-sm font-bold">Posting cost (₱)<input required type="number" min="0" step="0.01" value={form.listingFee} onChange={e=>setForm(v=>({...v,listingFee:e.target.value}))} className="mt-1 w-full rounded-xl border bg-white p-3 font-normal"/></label><label className="text-sm font-bold">Validity days<input required type="number" min="1" max="365" value={form.durationDays} onChange={e=>setForm(v=>({...v,durationDays:e.target.value}))} className="mt-1 w-full rounded-xl border bg-white p-3 font-normal"/></label><label className="text-sm font-bold">Maximum photos<input required type="number" min="1" max="20" value={form.maxPhotos} onChange={e=>setForm(v=>({...v,maxPhotos:e.target.value}))} className="mt-1 w-full rounded-xl border bg-white p-3 font-normal"/></label><label className="text-sm font-bold">Featured days<input required type="number" min="0" max="365" value={form.featuredDays} onChange={e=>setForm(v=>({...v,featuredDays:e.target.value}))} className="mt-1 w-full rounded-xl border bg-white p-3 font-normal"/></label><label className="flex items-center gap-2 self-end pb-3 text-sm font-bold sm:col-span-2"><input type="checkbox" checked={form.active} onChange={e=>setForm(v=>({...v,active:e.target.checked}))}/>Active and available to customers</label></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={closeForm} className="rounded-xl border bg-white px-4 py-2.5 font-bold">Cancel</button><button disabled={saving} className="rounded-xl bg-[#DB0002] px-5 py-2.5 font-black text-white disabled:opacity-50">{saving?'Saving…':editing?'Save Changes':'Create Plan'}</button></div></form>}
  {expanded&&<><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{plans.map(plan=><article key={plan.id} className={`rounded-xl border p-4 ${plan.active?'border-slate-200':'border-slate-200 bg-slate-50 opacity-65'}`}><div className="flex items-start justify-between gap-2"><div><p className="font-black">{plan.name}</p><span className={`mt-1 inline-block rounded-full px-2 py-0.5 text-[10px] font-black ${plan.active?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-600'}`}>{plan.active?'ACTIVE':'INACTIVE'}</span></div><button onClick={()=>open(plan)} aria-label={`Edit ${plan.name}`} className="rounded-lg border p-2 text-blue-700 hover:bg-blue-50"><Pencil size={15}/></button></div><p className="mt-4 text-2xl font-black text-[#DB0002]">{Number(plan.listingFee)===0?'FREE':`₱${Number(plan.listingFee).toLocaleString()}`}</p><p className="mt-1 text-sm font-bold">{plan.durationDays} days</p><p className="mt-2 text-xs text-slate-500">{plan.maxPhotos} photos · {plan.featuredDays} featured days</p></article>)}</div>{!plans.length&&!error&&<p className="mt-5 rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">No posting plans created yet.</p>}</>}
 </section>;
}
