'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ChevronDown, ChevronUp, Copy, Eye, EyeOff, Grid2X2, List, Plus, QrCode, RefreshCw } from 'lucide-react';
import toast from 'react-hot-toast';
import { inventoryApi, type DigitalMenuData, type DigitalMenuItem, type Product } from '@/lib/api';

type CatalogueRow = { product: Product; assignment: { isOnMenu?: boolean } | null };
type ViewMode = 'grid' | 'list';
const money = (value: unknown) => `₱${Number(value || 0).toLocaleString('en-PH', { maximumFractionDigits: 2 })}`;
const fallbackCategory = (item: DigitalMenuItem) => item.menuCategory || item.product.subCategory?.name || item.product.category?.name || 'Menu';
const variantName = (variant: NonNullable<Product['variants']>[number]) => variant.optionValues?.map(value => value.optionValue.value).join(' / ') || 'Option';

export default function DigitalMenuPage() {
  const [data, setData] = useState<DigitalMenuData | null>(null);
  const [catalogue, setCatalogue] = useState<CatalogueRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('All');
  const [availability, setAvailability] = useState('All');
  const [view, setView] = useState<ViewMode>('grid');
  const [addOpen, setAddOpen] = useState(false);
  const [editItem, setEditItem] = useState<DigitalMenuItem | null>(null);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [catalogueSearch, setCatalogueSearch] = useState('');
  const [selected, setSelected] = useState<number[]>([]);

  const load = useCallback(async () => {
    setError('');
    try {
      const [menu, products] = await Promise.all([inventoryApi.getDigitalMenu(), inventoryApi.getShopProducts()]);
      setData(menu); setCatalogue(products as CatalogueRow[]);
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load digital menu.'); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  const menuItems = useMemo(() => (data?.items || []).filter(item => item.isOnMenu), [data]);
  const categories = useMemo(() => [...new Set(menuItems.map(fallbackCategory))], [menuItems]);
  const visibleItems = useMemo(() => menuItems.filter(item => {
    const query = search.trim().toLowerCase();
    const matchesSearch = !query || [item.product.name, item.menuDescription || item.product.description, fallbackCategory(item)].some(value => value?.toLowerCase().includes(query));
    const matchesCategory = category === 'All' || fallbackCategory(item) === category;
    const matchesAvailability = availability === 'All' || (availability === 'Available' ? !item.soldOut : item.soldOut);
    return matchesSearch && matchesCategory && matchesAvailability;
  }), [availability, category, menuItems, search]);
  const grouped = useMemo(() => categories.map(name => ({ name, items: visibleItems.filter(item => fallbackCategory(item) === name) })).filter(group => group.items.length), [categories, visibleItems]);
  const availableCatalogue = useMemo(() => catalogue.filter(row => !menuItems.some(item => item.productId === row.product.id) && row.product.name.toLowerCase().includes(catalogueSearch.toLowerCase())), [catalogue, catalogueSearch, menuItems]);
  const publicMenuUrl = data ? `${typeof window === 'undefined' ? '' : window.location.origin}/merchants/${data.merchant.slug}?shop=${data.shop.id}` : '';

  const updateItem = async (item: DigitalMenuItem, patch: Record<string, unknown>, message = 'Menu item updated') => {
    try { await inventoryApi.updateDigitalMenuItem(item.productId, patch); await load(); toast.success(message); }
    catch (caught) { toast.error(caught instanceof Error ? caught.message : 'Unable to update menu item'); }
  };
  const moveItem = async (groupItems: DigitalMenuItem[], index: number, direction: -1 | 1) => {
    const target = index + direction; if (target < 0 || target >= groupItems.length) return;
    const reordered = [...groupItems]; [reordered[index], reordered[target]] = [reordered[target], reordered[index]];
    try { await inventoryApi.reorderDigitalMenu(reordered.map((item, position) => ({ productId: item.productId, menuCategory: fallbackCategory(item), menuCategoryOrder: item.menuCategoryOrder, menuDisplayOrder: position }))); await load(); }
    catch (caught) { toast.error(caught instanceof Error ? caught.message : 'Unable to save new menu order'); await load(); }
  };
  const moveCategory = async (index: number, direction: -1 | 1) => {
    const target = index + direction; if (target < 0 || target >= categories.length) return;
    const order = [...categories]; [order[index], order[target]] = [order[target], order[index]];
    try { await inventoryApi.reorderDigitalMenu(menuItems.map(item => ({ productId: item.productId, menuCategory: fallbackCategory(item), menuCategoryOrder: order.indexOf(fallbackCategory(item)), menuDisplayOrder: item.menuDisplayOrder }))); await load(); }
    catch (caught) { toast.error(caught instanceof Error ? caught.message : 'Unable to save category order'); await load(); }
  };
  const addSelected = async () => {
    try { await Promise.all(selected.map((productId, index) => inventoryApi.updateDigitalMenuItem(productId, { isOnMenu: true, menuVisible: true, menuDisplayOrder: menuItems.length + index }))); setSelected([]); setAddOpen(false); await load(); toast.success(`${selected.length} item${selected.length === 1 ? '' : 's'} added to the menu`); }
    catch (caught) { toast.error(caught instanceof Error ? caught.message : 'Unable to add menu items'); }
  };

  if (loading) return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-4">{[1,2,3].map(value => <div key={value} className="h-40 animate-pulse rounded-2xl bg-slate-200" />)}</div><div className="hidden h-[620px] animate-pulse rounded-3xl bg-slate-200 xl:block" /></div>;
  if (error || !data) return <div className="rounded-2xl border border-red-200 bg-red-50 p-8 text-center"><h1 className="text-xl font-black text-red-800">Unable to load digital menu.</h1><p className="mt-2 text-sm text-red-700">{error}</p><button onClick={() => { setLoading(true); void load(); }} className="mt-5 rounded-xl bg-red-600 px-5 py-3 font-bold text-white">Retry</button></div>;

  const preview = <MenuPreview data={data} items={menuItems.filter(item => item.menuVisible)} />;
  return <div className="space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-black text-slate-900">In-store Digital Menu</h1><p className="mt-1 text-slate-600">Build and arrange the menu customers see when they scan your QR.</p><p className="mt-3 text-sm font-bold text-red-600">{data.merchant.name}</p><p className="text-sm text-slate-500">{data.shop.name}{data.shop.isDefault ? ' · Main Branch' : ''}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setPreviewOpen(true)} className="rounded-xl border px-4 py-3 text-sm font-bold xl:hidden"><Eye className="mr-2 inline" size={17}/>Preview Menu</button><a href={publicMenuUrl} target="_blank" rel="noreferrer" className="hidden rounded-xl border px-4 py-3 text-sm font-bold xl:inline-flex"><Eye className="mr-2" size={17}/>Preview Menu</a><Link href="/shop/qr-codes" className="rounded-xl border px-4 py-3 text-sm font-bold"><QrCode className="mr-2 inline" size={17}/>QR Code</Link><button onClick={() => setAddOpen(true)} className="rounded-xl bg-red-600 px-4 py-3 text-sm font-black text-white"><Plus className="mr-2 inline" size={17}/>Add Menu Item</button></div></header>
    <section className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm sm:grid-cols-4"><Summary label="Menu Status" value="● LIVE" accent/><Summary label="Menu Items" value={String(menuItems.length)}/><Summary label="Categories" value={String(categories.length)}/><Summary label="Last Updated" value={menuItems.length ? new Date(Math.max(...menuItems.map(item => new Date(item.updatedAt).getTime()))).toLocaleString('en-PH', { dateStyle: 'medium', timeStyle: 'short' }) : 'Not yet updated'}/><p className="text-xs text-slate-500 sm:col-span-4">Changes are saved automatically and published to your live menu.</p></section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><main className="min-w-0 space-y-5"><section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_190px_auto]"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search menu items..." className="rounded-xl border px-4 py-3 text-sm"/><select value={availability} onChange={event => setAvailability(event.target.value)} className="rounded-xl border bg-white px-3"><option>All</option><option>Available</option><option>Sold Out</option></select><div className="flex rounded-xl bg-slate-100 p-1"><button aria-label="Grid view" onClick={() => setView('grid')} className={`rounded-lg p-2.5 ${view === 'grid' ? 'bg-white text-red-600 shadow' : 'text-slate-500'}`}><Grid2X2 size={18}/></button><button aria-label="List view" onClick={() => setView('list')} className={`rounded-lg p-2.5 ${view === 'list' ? 'bg-white text-red-600 shadow' : 'text-slate-500'}`}><List size={18}/></button></div></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1"><Chip active={category === 'All'} onClick={() => setCategory('All')}>All</Chip>{categories.map(name => <Chip key={name} active={category === name} onClick={() => setCategory(name)}>{name}</Chip>)}<button onClick={() => setAddOpen(true)} aria-label="Add menu item" className="min-w-10 rounded-full border border-dashed text-red-600">+</button></div></section>
      {!menuItems.length ? <section className="rounded-2xl border border-dashed bg-white py-20 text-center"><h2 className="text-xl font-black">Your digital menu is empty.</h2><p className="mt-2 text-slate-500">Choose products from your catalogue to start building your menu.</p><button onClick={() => setAddOpen(true)} className="mt-5 rounded-xl bg-red-600 px-5 py-3 font-black text-white">+ Add Menu Item</button></section> : grouped.map((group, groupIndex) => <section key={group.name} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black uppercase tracking-wide text-slate-900">{group.name}</h2><p className="text-xs text-slate-500">{group.items.length} item{group.items.length === 1 ? '' : 's'} · customer display order</p></div><div className="flex"><button onClick={() => void moveCategory(groupIndex,-1)} disabled={groupIndex===0} aria-label={`Move ${group.name} up`} className="p-2 disabled:opacity-30"><ChevronUp size={18}/></button><button onClick={() => void moveCategory(groupIndex,1)} disabled={groupIndex===categories.length-1} aria-label={`Move ${group.name} down`} className="p-2 disabled:opacity-30"><ChevronDown size={18}/></button></div></div><div className={view === 'grid' ? 'grid gap-4 md:grid-cols-2' : 'space-y-3'}>{group.items.map((item,index) => <MenuCard key={item.id} item={item} compact={view==='list'} onToggle={() => void updateItem(item,{ menuVisible: !item.menuVisible }, item.menuVisible ? 'Item hidden from customers' : 'Item visible to customers')} onEdit={() => setEditItem(item)} onRemove={() => void updateItem(item,{ isOnMenu:false },'Item removed from menu')} onMove={(direction) => void moveItem(group.items,index,direction)} canMoveUp={index>0} canMoveDown={index<group.items.length-1}/>)}</div><button onClick={() => setAddOpen(true)} className="mt-4 w-full rounded-xl border border-dashed p-3 text-sm font-bold text-red-600">+ Add Menu Item from Catalogue</button></section>)}</main>
      <aside className="hidden xl:block"><div className="sticky top-5 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Preview Menu</h2><p className="text-xs text-slate-500">What your customers see.</p></div><button onClick={() => void load()} aria-label="Refresh preview"><RefreshCw size={17}/></button></div>{preview}<label className="mt-4 block text-xs font-bold text-slate-600">Menu Link</label><div className="mt-1 flex gap-2"><input readOnly value={publicMenuUrl} className="min-w-0 flex-1 rounded-lg border bg-slate-50 px-2 text-xs"/><button onClick={() => { void navigator.clipboard.writeText(publicMenuUrl); toast.success('Menu link copied'); }} aria-label="Copy menu link" className="rounded-lg border p-2"><Copy size={16}/></button></div></div></aside></div>
    {addOpen && <Modal title="Choose from Catalogue" onClose={() => setAddOpen(false)}><input value={catalogueSearch} onChange={event => setCatalogueSearch(event.target.value)} placeholder="Search catalogue..." className="w-full rounded-xl border px-4 py-3"/><div className="mt-4 max-h-80 space-y-2 overflow-y-auto">{availableCatalogue.map(row => <label key={row.product.id} className="flex cursor-pointer items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={selected.includes(row.product.id)} onChange={event => setSelected(current => event.target.checked ? [...current,row.product.id] : current.filter(id => id!==row.product.id))}/>{row.product.imageUrl ? <img src={row.product.imageUrl} alt="" className="size-12 rounded-lg object-cover"/> : <div className="size-12 rounded-lg bg-slate-100"/>}<span><b className="block">{row.product.name}</b><small className="text-slate-500">{row.product.category?.name || 'Uncategorized'} · {money(row.product.discountPrice ?? row.product.sellingPrice ?? row.product.price)}</small></span></label>)}{!availableCatalogue.length && <p className="py-10 text-center text-sm text-slate-500">All matching catalogue products are already on the menu.</p>}</div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setAddOpen(false)} className="rounded-xl border px-4 py-2.5 font-bold">Cancel</button><button disabled={!selected.length} onClick={() => void addSelected()} className="rounded-xl bg-red-600 px-4 py-2.5 font-bold text-white disabled:opacity-40">Add Selected</button></div></Modal>}
    {editItem && <MenuEditor item={editItem} categories={categories} onClose={() => setEditItem(null)} onSave={async patch => { await updateItem(editItem,patch); setEditItem(null); }}/>} 
    {previewOpen && <Modal title="Preview Menu" onClose={() => setPreviewOpen(false)}>{preview}</Modal>}
  </div>;
}

function Summary({label,value,accent=false}:{label:string;value:string;accent?:boolean}) { return <div><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className={`mt-1 font-black ${accent ? 'text-green-600' : 'text-slate-900'}`}>{value}</p></div>; }
function Chip({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}) { return <button onClick={onClick} className={`shrink-0 rounded-full border px-4 py-2 text-xs font-bold ${active?'border-red-200 bg-red-50 text-red-600':'border-slate-200'}`}>{children}</button>; }
function MenuCard({item,compact,onToggle,onEdit,onRemove,onMove,canMoveUp,canMoveDown}:{item:DigitalMenuItem;compact:boolean;onToggle:()=>void;onEdit:()=>void;onRemove:()=>void;onMove:(direction:-1|1)=>void;canMoveUp:boolean;canMoveDown:boolean}) { const variants=item.product.variants?.filter(value=>value.isActive)||[]; return <article className={`overflow-hidden rounded-2xl border ${compact?'flex':'bg-white'}`}><div className={`relative bg-slate-100 ${compact?'w-36 shrink-0':'aspect-[4/3]'}`}>{item.product.imageUrl?<img src={item.product.imageUrl} alt={item.product.name} loading="lazy" className="size-full object-cover"/>:<div className="grid size-full place-items-center text-sm text-slate-400">No image</div>}<span className={`absolute left-2 top-2 rounded-full px-2 py-1 text-[10px] font-black ${item.menuVisible?'bg-green-100 text-green-800':'bg-slate-800 text-white'}`}>{item.menuVisible?'● Visible':'Hidden'}</span>{item.menuBadge&&<span className="absolute right-2 top-2 rounded-full bg-red-600 px-2 py-1 text-[10px] font-black text-white">{item.menuBadge}</span>}</div><div className="flex-1 p-4"><h3 className="font-black">{item.product.name}</h3><p className="mt-1 line-clamp-2 text-sm text-slate-500">{item.menuDescription||item.product.description||'Add a customer-facing description.'}</p><div className="mt-3 space-y-1 text-sm">{variants.length?variants.slice(0,4).map(variant=><div key={variant.id} className="flex justify-between"><span>{variantName(variant)}</span><b>{money(variant.price??item.effectivePrice)}</b></div>):<p className="font-black text-red-600">{money(item.effectivePrice)}</p>}</div><p className={`mt-2 text-xs font-bold ${item.soldOut?'text-red-600':'text-green-600'}`}>{item.soldOut?'Sold Out':'Available'}</p><div className="mt-4 flex flex-wrap items-center gap-2"><button onClick={onToggle} className="rounded-lg border px-3 py-2 text-xs font-bold">{item.menuVisible?<><EyeOff className="mr-1 inline" size={14}/>Hide</>:<><Eye className="mr-1 inline" size={14}/>Show</>}</button><button onClick={onEdit} className="rounded-lg border px-3 py-2 text-xs font-bold">Edit Menu</button><button onClick={onRemove} className="text-xs font-bold text-red-600">Remove</button><span className="ml-auto flex"><button onClick={()=>onMove(-1)} disabled={!canMoveUp} aria-label={`Move ${item.product.name} up`} className="p-1 disabled:opacity-25"><ChevronUp size={17}/></button><button onClick={()=>onMove(1)} disabled={!canMoveDown} aria-label={`Move ${item.product.name} down`} className="p-1 disabled:opacity-25"><ChevronDown size={17}/></button></span></div></div></article>; }
function MenuPreview({data,items}:{data:DigitalMenuData;items:DigitalMenuItem[]}) { return <div className="mx-auto mt-4 h-[520px] max-w-[280px] overflow-y-auto rounded-[28px] border-[6px] border-slate-900 bg-white"><div className="bg-red-600 p-4 text-white"><p className="font-black">{data.merchant.name}</p><p className="text-xs text-white/80">{data.shop.name}</p></div><div className="flex gap-1 overflow-x-auto p-3">{[...new Set(items.map(fallbackCategory))].map(name=><span key={name} className="shrink-0 rounded-full bg-red-50 px-2 py-1 text-[9px] font-bold text-red-600">{name}</span>)}</div><div className="space-y-3 p-3">{items.map(item=><div key={item.id} className="flex gap-2 border-b pb-3">{item.product.imageUrl?<img src={item.product.imageUrl} alt="" className="size-16 rounded-lg object-cover"/>:<div className="size-16 shrink-0 rounded-lg bg-slate-100"/>}<div className="min-w-0 flex-1"><div className="flex gap-1">{item.menuBadge&&<span className="rounded bg-red-50 px-1 text-[8px] font-black text-red-600">{item.menuBadge}</span>}{item.soldOut&&<span className="rounded bg-slate-100 px-1 text-[8px] font-black">SOLD OUT</span>}</div><p className="truncate text-xs font-black">{item.product.name}</p><p className="line-clamp-2 text-[9px] text-slate-500">{item.menuDescription||item.product.description}</p><p className="mt-1 text-xs font-black text-red-600">{item.product.variants?.length?'from ':''}{money(item.product.variants?.length?Math.min(...item.product.variants.map(value=>Number(value.price??item.effectivePrice))):item.effectivePrice)}</p></div></div>)}{!items.length&&<p className="py-16 text-center text-xs text-slate-400">No visible menu items.</p>}</div></div>; }
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" onMouseDown={onClose}><section onMouseDown={event=>event.stopPropagation()} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={onClose} aria-label="Close" className="text-2xl">×</button></div>{children}</section></div>; }
function MenuEditor({item,categories,onClose,onSave}:{item:DigitalMenuItem;categories:string[];onClose:()=>void;onSave:(patch:Record<string,unknown>)=>Promise<void>}) { const [description,setDescription]=useState(item.menuDescription||item.product.description||''); const [menuCategory,setMenuCategory]=useState(fallbackCategory(item)); const [badge,setBadge]=useState(item.menuBadge||''); const [saving,setSaving]=useState(false); return <Modal title={`Edit ${item.product.name}`} onClose={onClose}><div className="space-y-4"><label className="block text-sm font-bold">Menu Category<input list="menu-categories" value={menuCategory} onChange={event=>setMenuCategory(event.target.value)} className="mt-1 w-full rounded-xl border p-3 font-normal"/><datalist id="menu-categories">{categories.map(value=><option key={value}>{value}</option>)}</datalist></label><label className="block text-sm font-bold">Customer-facing description<textarea value={description} maxLength={300} onChange={event=>setDescription(event.target.value)} rows={4} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><label className="block text-sm font-bold">Badge<select value={badge} onChange={event=>setBadge(event.target.value as typeof badge)} className="mt-1 w-full rounded-xl border bg-white p-3 font-normal"><option value="">No badge</option><option>BESTSELLER</option><option>NEW</option><option>PROMO</option><option>FEATURED</option></select></label><p className="rounded-xl bg-slate-50 p-3 text-xs text-slate-600">Prices, SKUs, variants, and inventory remain managed in Catalogue Setup. <Link href="/shop/products" className="font-bold text-blue-700">Edit product details →</Link></p><div className="flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border px-4 py-2.5 font-bold">Cancel</button><button disabled={saving||!menuCategory.trim()} onClick={async()=>{setSaving(true);await onSave({menuDescription:description,menuCategory,menuBadge:badge||null,menuFeatured:badge==='FEATURED'});setSaving(false);}} className="rounded-xl bg-red-600 px-4 py-2.5 font-bold text-white disabled:opacity-50">{saving?'Saving…':'Save Menu Presentation'}</button></div></div></Modal>; }
