ALTER TABLE "merchants"
ADD COLUMN IF NOT EXISTS "tin" VARCHAR(30),
ADD COLUMN IF NOT EXISTS "registered_business_name" VARCHAR(255);

ALTER TABLE "branches"
ADD COLUMN IF NOT EXISTS "is_default" BOOLEAN NOT NULL DEFAULT FALSE;
