"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import toast from "react-hot-toast";
import { getToken } from "@/hooks/use-auth";
import { LockKeyhole, Monitor, Plus, RefreshCw, Smartphone, UserRound } from "lucide-react";

type Data={merchant:{name:string};shops:{id:number;name:string}[];currentShop:{id:number;name:string}|null;entitlement:{enabled:boolean;activeSubscription:boolean;source:string|null;limits:{maxCrewUsers?:number;maxCrewDevices?:number}};staff:any[];devices:any[]};
const emptyCrew={firstName:"",lastName:"",displayName:"",role:"SERVER",pin:""};
export default function CrewDevicesPage(){const[data,setData]=useState<Data|null>(null),[crew,setCrew]=useState(emptyCrew),[showCrew,setShowCrew]=useState(false),[showPair,setShowPair]=useState(false),[deviceRole,setDeviceRole]=useState("CREW_HANDHELD"),[pairCode,setPairCode]=useState<any>(null),[saving,setSaving]=useState(false);
const load=useCallback(()=>fetch(`/api/backend/dine-in-crew/overview?updated=${Date.now()}`,{headers:{Authorization:`Bearer ${getToken()}`},cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error("Unable to load Crew & Devices");setData(await r.json())}).catch(e=>toast.error(e.message)),[]); useEffect(()=>{void load();const interval=window.setInterval(()=>void load(),60_000);const refresh=()=>void load();window.addEventListener("focus",refresh);document.addEventListener("visibilitychange",refresh);return()=>{window.clearInterval(interval);window.removeEventListener("focus",refresh);document.removeEventListener("visibilitychange",refresh)}},[load]);
async function request(path:string,method:string,body?:any){const r=await fetch(`/api/backend${path}`,{method,headers:{"Content-Type":"application/json",Authorization:`Bearer ${getToken()}`},body:body?JSON.stringify(body):undefined});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof x.message==="string"?x.message:x.message?.message||"Request failed");return x}
async function addCrew(){setSaving(true);try{await request("/dine-in-crew/crew","POST",crew);toast.success("Crew member registered");setCrew(emptyCrew);setShowCrew(false);await load()}catch(e){toast.error(e instanceof Error?e.message:"Unable to register crew")}finally{setSaving(false)}}
async function generate(){setSaving(true);try{const x=await request("/dine-in-crew/pairings","POST",{role:deviceRole});setPairCode(x)}catch(e){toast.error(e instanceof Error?e.message:"Unable to generate pairing code")}finally{setSaving(false)}}
if(!data)return <div className="p-8">Loading Crew & Devices…</div>; const enabled=data.entitlement.enabled;
return <main className="space-y-5 p-4 lg:p-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black text-red-600">{data.currentShop?.name || data.merchant.name}</p><h1 className="text-3xl font-black">Crew & Devices</h1><p className="text-sm text-slate-500">Register dine-in crew and pair devices for this shop.</p></div><button onClick={()=>void load()} className="flex min-h-11 items-center gap-2 rounded-xl border px-4 font-bold"><RefreshCw size={17}/> Refresh</button></header>
<section className={`rounded-2xl border p-5 ${enabled?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}>{enabled?<><p className="font-black text-emerald-900">✓ Dine-In Crew enabled</p><p className="text-xs text-emerald-700">Entitled through {data.entitlement.source}. Crew and device limits are enforced by the backend.</p></>:<div className="flex gap-3"><LockKeyhole className="text-amber-700"/><div><p className="font-black text-amber-950">Crew & Device Management is locked</p><p className="mt-1 text-sm text-amber-800">{data.entitlement.activeSubscription?"This feature is not included in your current entitlements.":"Your merchant subscription is inactive."}</p><p className="mt-2 text-xs text-amber-800">Upgrade to let crew take dine-in orders from authorized handhelds. Your existing crew and devices remain saved.</p><Link href="/merchant/subscription/upgrade" className="mt-3 inline-flex min-h-10 items-center rounded-lg bg-amber-900 px-4 font-bold text-white">View Plans</Link></div></div>}</section>
<div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Restaurant crew</h2><p className="text-xs text-slate-500">Each person uses their own secure PIN.</p></div><button disabled={!enabled} onClick={()=>setShowCrew(true)} className="flex min-h-10 items-center gap-1 rounded-lg bg-red-600 px-3 font-bold text-white disabled:bg-slate-300"><Plus size={16}/> Add Crew</button></div><div className="mt-4 space-y-2">{data.staff.filter(s=>s.role).map(s=><article key={s.id} className="flex items-center justify-between rounded-xl border p-3"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-purple-100 text-purple-700"><UserRound size={19}/></span><div><p className="font-black">{s.displayName}</p><p className="text-xs text-slate-500">{s.role} · {s.branch?.name||"All shops"} · PIN {s.hasPin?"set":"missing"}</p></div></div><button disabled={!enabled} onClick={async()=>{await request(`/dine-in-crew/crew/${s.id}`,"PATCH",{isActive:!s.isActive});await load()}} className={`rounded-full px-3 py-1 text-xs font-black ${s.isActive?"bg-green-100 text-green-700":"bg-slate-200 text-slate-600"}`}>{s.isActive?"Active":"Inactive"}</button></article>)}{!data.staff.some(s=>s.role)&&<p className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">No dine-in crew registered.</p>}</div></section>
<section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Authorized devices</h2><p className="text-xs text-slate-500">Lost devices can be revoked immediately.</p></div><button disabled={!enabled} onClick={()=>setShowPair(true)} className="flex min-h-10 items-center gap-1 rounded-lg bg-red-600 px-3 font-bold text-white disabled:bg-slate-300"><Plus size={16}/> Register Device</button></div><div className="mt-4 space-y-2">{data.devices.map(d=><article key={d.id} className="flex items-center justify-between rounded-xl border p-3"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-700">{d.role==="PRIMARY_COUNTER"?<Monitor size={20}/>:<Smartphone size={20}/>}</span><div><p className="font-black">{d.name}</p><p className="text-xs text-slate-500">{d.shop?.name} · {d.role.replaceAll("_"," ")} · {d.status}</p></div></div>{d.status==="active"&&<button disabled={!enabled} onClick={async()=>{await request(`/dine-in-crew/devices/${d.id}/revoke`,"PATCH");await load()}} className="text-xs font-bold text-red-600">Revoke</button>}</article>)}{!data.devices.length&&<p className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">No authorized devices.</p>}</div></section></div>
{showCrew&&<Modal title="Add dine-in crew" close={()=>setShowCrew(false)}><div className="rounded-xl bg-slate-50 p-3 text-xs"><span className="text-slate-500">Shop</span><p className="font-black">{data.currentShop?.name}</p></div><div className="grid grid-cols-2 gap-3"><Input label="First name" value={crew.firstName} set={v=>setCrew({...crew,firstName:v})}/><Input label="Last name" value={crew.lastName} set={v=>setCrew({...crew,lastName:v})}/></div><Input label="Display name" value={crew.displayName} set={v=>setCrew({...crew,displayName:v})}/><label className="block text-xs font-bold">Role<select value={crew.role} onChange={e=>setCrew({...crew,role:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border px-3">{["WAITER","SERVER","CASHIER","SUPERVISOR","MANAGER"].map(x=><option key={x}>{x}</option>)}</select></label><Input label="4–6 digit Crew PIN" value={crew.pin} set={v=>setCrew({...crew,pin:v.replace(/\D/g,"").slice(0,6)})}/><button disabled={saving} onClick={()=>void addCrew()} className="min-h-12 w-full rounded-xl bg-red-600 font-black text-white">Register Crew</button></Modal>}
{showPair&&<Modal title="Register authorized device" close={()=>{setShowPair(false);setPairCode(null)}}>{pairCode?<div className="text-center"><p className="text-sm font-bold text-slate-700">Scan this QR using the crew device</p><p className="mt-1 text-xs text-slate-500">The device is paired first, then the crew member enters their personal PIN.</p><img src={pairCode.qrCode} alt="Crew device pairing QR code" className="mx-auto my-4 size-64 rounded-xl border bg-white p-2"/><div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Or enter pairing code</p><p className="mt-1 text-3xl font-black tracking-[.25em] text-red-600">{pairCode.code}</p></div><p className="mt-3 text-xs text-slate-500">Single use · Expires in 10 minutes</p><Link href={pairCode.pairingUrl || "/crew/pair"} target="_blank" className="mt-3 inline-block font-bold text-red-600">Open pairing page →</Link></div>:<><div className="rounded-xl bg-slate-50 p-3 text-xs"><span className="text-slate-500">Shop detected</span><p className="font-black">{data.currentShop?.name}</p></div><label className="block text-xs font-bold">Device role<select value={deviceRole} onChange={e=>setDeviceRole(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"><option value="CREW_HANDHELD">Crew Handheld</option><option value="PRIMARY_COUNTER">Primary Counter</option></select></label><button disabled={saving||!data.currentShop} onClick={()=>void generate()} className="min-h-12 w-full rounded-xl bg-red-600 font-black text-white disabled:bg-slate-300">Generate pairing QR</button></>}</Modal>}</main>}
function Input({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="block text-xs font-bold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md space-y-4 rounded-2xl bg-white p-5 shadow-xl"><div className="flex justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={close}>✕</button></div>{children}</div></div>}
