import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { sign } from 'jsonwebtoken';
import { cpSync, existsSync, mkdirSync, rmSync } from 'fs';
import { join } from 'path';
import { randomUUID } from 'crypto';
import { AgreementAcceptanceMethod, AgreementEvidenceType, AgreementPartyRole, AgreementProvenance, CustodyEventType, UserRole } from '@prisma/client';
import { AppModule } from '../app.module';
import { PrismaService } from '../prisma/prisma.service';
import { AgreementService } from './agreement.service';

describe('Stage 2B agreements HTTP acceptance', () => {
  let app: INestApplication; let prisma: PrismaService; let agreements: AgreementService;
  let customerA: any; let customerB: any; let merchantUserA: any; let merchantUserB: any; let rider: any; let merchantA: any; let merchantB: any; let orderA: any; let orderB: any; let agreementA: any;
  const runtimeI18n = join(process.cwd(), 'i18n'); const sourceI18n = join(process.cwd(), 'src', 'i18n');
  const auth = (u: any) => ({ Authorization: `Bearer ${sign({ sub: u.id, role: u.role }, process.env.JWT_SECRET || 'dev-secret', { expiresIn: '1h' })}` });
  beforeAll(async () => { if (!existsSync(runtimeI18n)) { mkdirSync(runtimeI18n, { recursive: true }); cpSync(sourceI18n, runtimeI18n, { recursive: true }); } const mod = await Test.createTestingModule({ imports: [AppModule] }).compile(); app = mod.createNestApplication(); await app.init(); prisma = app.get(PrismaService); agreements = app.get(AgreementService); });
  beforeEach(async () => {
    const tag = randomUUID(); const user = (role: UserRole) => prisma.user.create({ data: { phone: `+63${randomUUID().replace(/-/g, '').slice(0, 16)}`, email: `${tag}-${role}-${randomUUID()}@test.invalid`, role } });
    customerA = await user(UserRole.customer); customerB = await user(UserRole.customer); merchantUserA = await user(UserRole.merchant); merchantUserB = await user(UserRole.merchant); rider = await user(UserRole.rider);
    merchantA = await prisma.merchant.create({ data: { userId: merchantUserA.id, name: `A ${tag}`, slug: `s2b-a-${tag}` } }); merchantB = await prisma.merchant.create({ data: { userId: merchantUserB.id, name: `B ${tag}`, slug: `s2b-b-${tag}` } });
    const order = (userId: string, merchantId: number, code: string) => prisma.wkOrder.create({ data: { orderCode: code, userId, merchantId, status: 'pending', orderType: 'delivery', totalAmount: 100, deliveryFee: 0, transactionFeeAmount: 0, paymentMethod: 'cod', paymentStatus: 'pending', orderItems: { create: [{ productName: 'item', quantity: 1, price: 100, subtotal: 100 }] } } });
    orderA = await order(customerA.id, merchantA.id, `S2B-A-${tag}`); orderB = await order(customerB.id, merchantB.id, `S2B-B-${tag}`); agreementA = await agreements.offerMerchantTradeForOrder(orderA.id, { provenance: AgreementProvenance.LEGACY_SNAPSHOT });
  });
  afterEach(async () => { const ids = [orderA?.id, orderB?.id].filter(Boolean); const ags = await prisma.agreement.findMany({ where: { wkOrderId: { in: ids } } }); for (const ag of ags) { await prisma.agreementAcceptance.deleteMany({ where: { agreementVersion: { agreementId: ag.id } } }); await prisma.custodyEventEvidence.deleteMany({ where: { custodyEvent: { agreementId: ag.id } } }); await prisma.custodyEvent.deleteMany({ where: { agreementId: ag.id } }); await prisma.agreementEvidence.deleteMany({ where: { agreementId: ag.id } }); await prisma.agreementParty.deleteMany({ where: { agreementId: ag.id } }); await prisma.agreement.update({ where: { id: ag.id }, data: { currentVersionId: null } }); await prisma.agreementVersion.deleteMany({ where: { agreementId: ag.id } }); await prisma.orderDomainEvent.deleteMany({ where: { aggregateId: ag.id } }); await prisma.agreement.delete({ where: { id: ag.id } }); } await prisma.orderItem.deleteMany({ where: { orderId: { in: ids } } }); await prisma.wkOrder.deleteMany({ where: { id: { in: ids } } }); await prisma.merchant.deleteMany({ where: { id: { in: [merchantA?.id, merchantB?.id].filter(Boolean) } } }); await prisma.user.deleteMany({ where: { id: { in: [customerA?.id, customerB?.id, merchantUserA?.id, merchantUserB?.id, rider?.id].filter(Boolean) } } }); });
  afterAll(async () => { await app?.close(); if (existsSync(runtimeI18n)) rmSync(runtimeI18n, { recursive: true, force: true }); });
  it('denies unauthenticated agreement, integrity, evidence, and custody routes', async () => { await request(app.getHttpServer()).get(`/agreements/${agreementA.id}`).expect(401); await request(app.getHttpServer()).get(`/agreement-versions/${agreementA.currentVersionId}/integrity`).expect(401); await request(app.getHttpServer()).post(`/agreements/${agreementA.id}/evidence`).send({ evidenceType: 'DOCUMENT' }).expect(401); await request(app.getHttpServer()).get(`/orders/${orderA.id}/custody-events`).expect(401); });
  it('scopes agreement and integrity reads to parties, not guessed identifiers', async () => { await request(app.getHttpServer()).get(`/agreements/${agreementA.id}`).set(auth(customerA)).expect(200); await request(app.getHttpServer()).get(`/agreements/${agreementA.id}`).set(auth(customerB)).expect(403); await request(app.getHttpServer()).get(`/agreements/${agreementA.id}`).set(auth(merchantUserA)).expect(200); await request(app.getHttpServer()).get(`/agreements/${agreementA.id}`).set(auth(merchantUserB)).expect(403); await request(app.getHttpServer()).get(`/agreement-versions/${agreementA.currentVersionId}/integrity`).set(auth(customerA)).expect(200); await request(app.getHttpServer()).get(`/agreement-versions/${agreementA.currentVersionId}/integrity`).set(auth(customerB)).expect(403); });
  it('derives acceptance identity and rejects spoofed roles and inactive methods', async () => { const version = await prisma.agreementVersion.findUniqueOrThrow({ where: { id: agreementA.currentVersionId } }); await request(app.getHttpServer()).post(`/agreement-versions/${version.id}/accept`).set(auth(customerB)).send({ partyRole: 'CUSTOMER', actorUserId: customerA.id }).expect(403); await request(app.getHttpServer()).post(`/agreement-versions/${version.id}/accept`).set(auth(customerA)).send({ partyRole: 'MERCHANT', termsHash: 'attacker', method: 'WEB_CONFIRMATION' }).expect(403); await request(app.getHttpServer()).post(`/agreement-versions/${version.id}/accept`).set(auth(customerA)).send({ partyRole: 'CUSTOMER', method: AgreementAcceptanceMethod.QR_CONFIRMATION }).expect(400); const ok = await request(app.getHttpServer()).post(`/agreement-versions/${version.id}/accept`).set(auth(customerA)).send({ partyRole: 'CUSTOMER', method: 'WEB_CONFIRMATION', termsHash: 'attacker' }).expect(201); expect(ok.body.acceptance.actorUserId).toBe(customerA.id); expect(ok.body.acceptance.termsHash).toBe(version.termsHash); });
  it('keeps evidence idempotent and custody scoped without mutating fulfillment/payment', async () => { const key = `e-${randomUUID()}`; const first = await request(app.getHttpServer()).post(`/agreements/${agreementA.id}/evidence`).set(auth(customerA)).send({ evidenceType: AgreementEvidenceType.DOCUMENT, storageReference: 'private-ref', idempotencyKey: key }).expect(201); const second = await request(app.getHttpServer()).post(`/agreements/${agreementA.id}/evidence`).set(auth(customerA)).send({ evidenceType: AgreementEvidenceType.DOCUMENT, storageReference: 'private-ref', idempotencyKey: key }).expect(201); expect(second.body.idempotent).toBe(true); expect(second.body.evidence.id).toBe(first.body.evidence.id); await request(app.getHttpServer()).post('/custody-events').set(auth(customerB)).send({ wkOrderId: orderA.id, eventType: CustodyEventType.CUSTOMER_RECEIVED }).expect(403); await request(app.getHttpServer()).post('/custody-events').set(auth(customerA)).send({ wkOrderId: orderA.id, agreementId: agreementA.id, eventType: CustodyEventType.CUSTOMER_RECEIVED, fromUserId: customerB.id }).expect(403); await request(app.getHttpServer()).post('/custody-events').set(auth(customerA)).send({ wkOrderId: orderA.id, agreementId: agreementA.id, eventType: CustodyEventType.CUSTOMER_RECEIVED, evidenceIds: [first.body.evidence.id] }).expect(403); expect(await prisma.custodyEvent.count({ where: { wkOrderId: orderA.id, eventType: CustodyEventType.CUSTOMER_RECEIVED } })).toBe(0); const order = await prisma.wkOrder.findUniqueOrThrow({ where: { id: orderA.id } }); expect(order.paymentStatus).toBe('pending'); expect(order.status).toBe('pending'); });
});
