'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Building2, List, LocateFixed, Map, Search } from 'lucide-react';
import PropertyCard from '@/components/PropertyCard';
import { propertyApi, type PropertyListing, type PropertyType } from '@/lib/property';
import { useUserLocation } from '@/hooks/use-geolocation';
import dynamic from 'next/dynamic';

const PropertyMap = dynamic(() => import('@/components/PropertyMap'), { ssr: false });

export default function PropertyPage() {
  const { coords } = useUserLocation(); const [types,setTypes]=useState<PropertyType[]>([]), [items,setItems]=useState<PropertyListing[]>([]), [loading,setLoading]=useState(true), [error,setError]=useState(''), [view,setView]=useState<'LIST'|'MAP'>('LIST');
  const [filters,setFilters]=useState({ transactionType:'',propertyTypeId:'',keyword:'',city:'',minPrice:'',maxPrice:'',bedrooms:'',distance:'' });
  useEffect(()=>{propertyApi.types().then(setTypes).catch(()=>setError('Unable to load property types.'));},[]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const p=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>v&&p.set(k,v));if(coords){p.set('latitude',String(coords.lat));p.set('longitude',String(coords.lng));}p.set('limit','24');const result=await propertyApi.browse(p);setItems(result.items);}catch(e){setError(e instanceof Error?e.message:'Unable to load properties.');}finally{setLoading(false);}},[filters,coords]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer);},[load]);
  const groups=useMemo(()=>Object.entries(types.reduce<Record<string,PropertyType[]>>((a,t)=>{(a[t.groupName]??=[]).push(t);return a;},{})),[types]);
  return <>
    <section className="bg-gradient-to-br from-[#102a69] via-[#1746a2] to-[#2563eb] px-4 py-10 text-white sm:py-14"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.24em] text-blue-200">WEKONNEK Property</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Find Property Near You</h1><p className="mt-3 max-w-2xl text-sm text-blue-100 sm:text-lg">Homes, condos, lots and commercial spaces for sale or rent.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>setFilters(f=>({...f,transactionType:'FOR_SALE'}))} className={`rounded-xl px-6 py-3 font-black ${filters.transactionType==='FOR_SALE'?'bg-[#DB0002]':'bg-white text-slate-950'}`}>For Sale</button><button onClick={()=>setFilters(f=>({...f,transactionType:'FOR_RENT'}))} className={`rounded-xl px-6 py-3 font-black ${filters.transactionType==='FOR_RENT'?'bg-[#DB0002]':'bg-white text-slate-950'}`}>For Rent</button><Link href="/property/post" className="rounded-xl border border-white/40 px-6 py-3 font-black">+ Post Property</Link></div></div></section>
    <div className="mx-auto max-w-7xl px-4 py-6"><div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1.5fr_1fr_auto]"><label className="flex items-center gap-2 rounded-xl border px-3"><Search size={18} className="text-slate-400"/><input value={filters.keyword} onChange={e=>setFilters(f=>({...f,keyword:e.target.value}))} placeholder="Search condo, house, city or barangay" className="w-full py-3 outline-none"/></label><input value={filters.city} onChange={e=>setFilters(f=>({...f,city:e.target.value}))} placeholder="City" className="rounded-xl border px-4 py-3"/><div className="flex rounded-xl bg-slate-100 p-1"><button onClick={()=>setView('LIST')} className={`flex items-center gap-1 rounded-lg px-3 font-bold ${view==='LIST'?'bg-white shadow':''}`}><List size={17}/>List</button><button onClick={()=>setView('MAP')} className={`flex items-center gap-1 rounded-lg px-3 font-bold ${view==='MAP'?'bg-white shadow':''}`}><Map size={17}/>Map</button></div></div>
      <div className="mt-3 flex gap-2 overflow-x-auto pb-1"><select value={filters.propertyTypeId} onChange={e=>setFilters(f=>({...f,propertyTypeId:e.target.value}))} className="rounded-full border bg-white px-4 py-2 text-sm font-semibold"><option value="">All property types</option>{groups.map(([group,list])=><optgroup label={group} key={group}>{list.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</optgroup>)}</select><input type="number" value={filters.minPrice} onChange={e=>setFilters(f=>({...f,minPrice:e.target.value}))} placeholder="Min price" className="w-32 rounded-full border px-4 text-sm"/><input type="number" value={filters.maxPrice} onChange={e=>setFilters(f=>({...f,maxPrice:e.target.value}))} placeholder="Max price" className="w-32 rounded-full border px-4 text-sm"/><select value={filters.bedrooms} onChange={e=>setFilters(f=>({...f,bedrooms:e.target.value}))} className="rounded-full border bg-white px-4 text-sm"><option value="">Any bedrooms</option><option value="1">1+ bedroom</option><option value="2">2+ bedrooms</option><option value="3">3+ bedrooms</option></select><select value={filters.distance} onChange={e=>setFilters(f=>({...f,distance:e.target.value}))} className="rounded-full border bg-white px-4 text-sm"><option value="">Any distance</option>{[1,3,5,10].map(n=><option value={n} key={n}>Within {n} km</option>)}</select><button onClick={()=>setFilters({transactionType:'',propertyTypeId:'',keyword:'',city:'',minPrice:'',maxPrice:'',bedrooms:'',distance:''})} className="rounded-full border px-4 text-sm font-bold">Clear</button></div></div>
      <div className="mt-7 flex items-end justify-between"><div><h2 className="text-2xl font-black">{filters.transactionType==='FOR_RENT'?'Properties for Rent':filters.transactionType==='FOR_SALE'?'Properties for Sale':'Properties Near You'}</h2><p className="text-sm text-slate-500">{items.length} matching properties</p></div>{coords&&<span className="hidden items-center gap-1 text-xs font-bold text-blue-700 sm:flex"><LocateFixed size={15}/>Distance enabled</span>}</div>
      {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}{loading?<div className="grid grid-cols-1 gap-5 py-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{[1,2,3,4].map(n=><div key={n} className="h-80 animate-pulse rounded-2xl bg-slate-200"/>)}</div>:view==='MAP'?<PropertyMap listings={items} center={coords}/>:items.length?<div className="grid grid-cols-1 gap-5 py-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(item=><PropertyCard key={item.id} listing={item}/>)}</div>:<div className="py-20 text-center"><Building2 className="mx-auto text-slate-300" size={56}/><h3 className="mt-4 text-xl font-black">No properties found</h3><p className="text-slate-500">Try widening your search or be the first to post here.</p></div>}
    </div>
  </>;
}
