import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { sign } from 'jsonwebtoken';
import { cpSync, existsSync, mkdirSync, rmSync } from 'fs';
import { join } from 'path';
import { randomUUID } from 'crypto';
import { CommerceDomain, FulfillmentStatus, UserRole } from '@prisma/client';
import { AppModule } from '../app.module';
import { PrismaService } from '../prisma/prisma.service';
import { RiderAssignmentService } from '../fulfillment/rider-assignment.service';

describe('Stage 3B pickup handoff HTTP acceptance', () => {
  let app: INestApplication; let prisma: PrismaService; let assignments: RiderAssignmentService;
  let customer: any; let riderA: any; let riderB: any; let merchantUser: any; let otherMerchantUser: any; let merchant: any; let otherMerchant: any; let order: any; let fulfillment: any;
  const runtimeI18n = join(process.cwd(), 'i18n'); const sourceI18n = join(process.cwd(), 'src', 'i18n');
  const auth = (u: any) => ({ Authorization: `Bearer ${sign({ sub: u.id, role: u.role }, process.env.JWT_SECRET || 'dev-secret', { expiresIn: '1h' })}` });
  beforeAll(async()=>{if(!existsSync(runtimeI18n)){mkdirSync(runtimeI18n,{recursive:true});cpSync(sourceI18n,runtimeI18n,{recursive:true});}const mod=await Test.createTestingModule({imports:[AppModule]}).compile();app=mod.createNestApplication();await app.init();prisma=app.get(PrismaService);assignments=app.get(RiderAssignmentService);});
  beforeEach(async()=>{const tag=randomUUID();const user=(role:UserRole)=>prisma.user.create({data:{phone:`+63${randomUUID().replace(/-/g,'').slice(0,16)}`,email:`s3b-${tag}-${role}-${randomUUID()}@test.invalid`,role}});customer=await user(UserRole.customer);riderA=await user(UserRole.rider);riderB=await user(UserRole.rider);merchantUser=await user(UserRole.merchant);otherMerchantUser=await user(UserRole.merchant);merchant=await prisma.merchant.create({data:{userId:merchantUser.id,name:`S3B ${tag}`,slug:`s3b-${tag}`,commerceDomain:CommerceDomain.NON_FOOD}});otherMerchant=await prisma.merchant.create({data:{userId:otherMerchantUser.id,name:`S3B other ${tag}`,slug:`s3b-o-${tag}`,commerceDomain:CommerceDomain.NON_FOOD}});order=await prisma.wkOrder.create({data:{orderCode:`WK-S3B-${tag.slice(0,8)}`,userId:customer.id,merchantId:merchant.id,status:'pending',orderType:'delivery',totalAmount:100,deliveryFee:0,transactionFeeAmount:0,paymentMethod:'cod',paymentStatus:'pending',orderItems:{create:[{productName:'item',quantity:1,price:100,subtotal:100}]}}});fulfillment=await prisma.orderFulfillment.create({data:{id:randomUUID(),wkOrderId:order.id,merchantId:merchant.id,customerId:customer.id,status:FulfillmentStatus.ready_for_pickup,assignmentVersion:0}});await assignments.assign({fulfillmentId:fulfillment.id,riderId:riderA.id,actor:{type:'SYSTEM'}});});
  afterEach(async()=>{const tokens=await prisma.pickupHandoffToken.findMany({where:{wkOrderId:order?.id}});const custodyIds=tokens.map(t=>t.custodyEventId).filter(Boolean) as string[];await prisma.orderDomainEvent.deleteMany({where:{wkOrderId:order?.id}});await prisma.pickupHandoffToken.deleteMany({where:{wkOrderId:order?.id}});if(custodyIds.length)await prisma.custodyEvent.deleteMany({where:{id:{in:custodyIds}}});await prisma.riderAssignment.deleteMany({where:{fulfillmentId:fulfillment?.id}});await prisma.orderFulfillment.deleteMany({where:{id:fulfillment?.id}});await prisma.orderItem.deleteMany({where:{orderId:order?.id}});await prisma.wkOrder.deleteMany({where:{id:order?.id}});await prisma.merchant.deleteMany({where:{id:{in:[merchant?.id,otherMerchant?.id].filter(Boolean)}}});await prisma.user.deleteMany({where:{id:{in:[customer?.id,riderA?.id,riderB?.id,merchantUser?.id,otherMerchantUser?.id].filter(Boolean)}}});});
  afterAll(async()=>{await app?.close();if(existsSync(runtimeI18n))rmSync(runtimeI18n,{recursive:true,force:true});});
  it('denies anonymous issuance, preview, and confirmation',async()=>{await request(app.getHttpServer()).post(`/orders/${order.id}/pickup-token`).expect(401);await request(app.getHttpServer()).post('/pickup-handoffs/validate').send({qrPayload:'garbage'}).expect(401);await request(app.getHttpServer()).post('/pickup-handoffs/confirm').send({qrPayload:'garbage'}).expect(401);});
  it('enforces assigned-rider issuance and merchant-private preview',async()=>{const issued=await request(app.getHttpServer()).post(`/orders/${order.id}/pickup-token`).set(auth(riderA)).send({riderId:riderB.id}).expect(403);expect(issued.body.message).toContain('Rider identity');await request(app.getHttpServer()).post(`/orders/${order.id}/pickup-token`).set(auth(riderB)).expect(403);const good=await request(app.getHttpServer()).post(`/orders/${order.id}/pickup-token`).set(auth(riderA)).expect(201);await request(app.getHttpServer()).post('/pickup-handoffs/validate').set(auth(otherMerchantUser)).send({qrPayload:good.body.qrPayload}).expect(201).expect(r=>expect(r.body.ok).toBe(false));const preview=await request(app.getHttpServer()).post('/pickup-handoffs/validate').set(auth(merchantUser)).send({qrPayload:good.body.qrPayload}).expect(201);expect(preview.body.ok).toBe(true);expect(preview.body.preview.orderCode).toBe(order.orderCode);const token=await prisma.pickupHandoffToken.findUniqueOrThrow({where:{id:good.body.tokenId}});expect(token.status).toBe('ACTIVE');expect(token.tokenHash).not.toContain(good.body.qrPayload.split('.').pop());});
  it('rejects malformed QR without side effects and completes exactly one authoritative handoff',async()=>{const issued=await request(app.getHttpServer()).post(`/orders/${order.id}/pickup-token`).set(auth(riderA)).expect(201);for(const qrPayload of ['', 'junk', 'WKPH1.a.b', 'WKPH2.x.y', `${issued.body.qrPayload}x`]){const r=await request(app.getHttpServer()).post('/pickup-handoffs/confirm').set(auth(merchantUser)).send({qrPayload}).expect(201);expect(r.body.ok).toBe(false);}const before=await prisma.orderFulfillment.findUniqueOrThrow({where:{id:fulfillment.id}});expect(before.status).toBe('rider_assigned');const confirmed=await request(app.getHttpServer()).post('/pickup-handoffs/confirm').set(auth(merchantUser)).send({qrPayload:issued.body.qrPayload}).expect(201);expect(confirmed.body.ok).toBe(true);const replay=await request(app.getHttpServer()).post('/pickup-handoffs/confirm').set(auth(merchantUser)).send({qrPayload:issued.body.qrPayload}).expect(201);expect(replay.body.idempotent).toBe(true);expect(await prisma.custodyEvent.count({where:{wkOrderId:order.id,eventType:'MERCHANT_RELEASED'}})).toBe(1);expect((await prisma.orderFulfillment.findUniqueOrThrow({where:{id:fulfillment.id}})).status).toBe('picked_up');});
  it('invalidates a previewed rider A token after canonical reassignment and accepts rider B capability',async()=>{const old=await request(app.getHttpServer()).post(`/orders/${order.id}/pickup-token`).set(auth(riderA)).expect(201);await request(app.getHttpServer()).post('/pickup-handoffs/validate').set(auth(merchantUser)).send({qrPayload:old.body.qrPayload}).expect(201);await assignments.assign({fulfillmentId:fulfillment.id,riderId:riderB.id,actor:{type:'SYSTEM'},allowReassignment:true});const stale=await request(app.getHttpServer()).post('/pickup-handoffs/confirm').set(auth(merchantUser)).send({qrPayload:old.body.qrPayload}).expect(201);expect(stale.body.ok).toBe(false);expect((await prisma.orderFulfillment.findUniqueOrThrow({where:{id:fulfillment.id}})).status).toBe('rider_assigned');const fresh=await request(app.getHttpServer()).post(`/orders/${order.id}/pickup-token`).set(auth(riderB)).expect(201);await request(app.getHttpServer()).post('/pickup-handoffs/confirm').set(auth(merchantUser)).send({qrPayload:fresh.body.qrPayload}).expect(201).expect(r=>expect(r.body.ok).toBe(true));});
});
