import { BadRequestException, Injectable, NotImplementedException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../prisma/prisma.service';

const PROVIDER = 'PAYCOOLS';
const SOURCE_DEFAULTS: Record<string, boolean> = { RESTAURANT_ORDER: true, RETAIL_ORDER: true, ADVANCE_ORDER: true, TAKE_OUT: true, RESERVATION: true, MERCHANT_SUBSCRIPTION: true, DELIVERY_ORDER: false, SERVICE_BOOKING: false, BAZAAR_LISTING: false, PROPERTY_LISTING: false };
const MUTABLE_FIELDS = ['enabled', 'environment', 'dynamicQrEnabled', 'defaultQrExpirySeconds', 'refundEnabled', 'payoutEnabled', 'settlementMode', 'uatPublicKeyRegistrationConfirmed', 'uatIpWhitelistConfirmed', 'uatCallbackRegistrationConfirmed', 'prodPublicKeyRegistrationConfirmed', 'prodIpWhitelistConfirmed', 'prodCallbackRegistrationConfirmed'] as const;
type Environment = 'uat' | 'production';

@Injectable()
export class PaymentPartnerConfigService {
  constructor(private prisma: PrismaService, private env: ConfigService) {}

  private async ensureConfig() { return this.prisma.paymentPartnerConfiguration.upsert({ where: { providerCode: PROVIDER }, update: {}, create: { providerCode: PROVIDER, enabled: false, environment: 'uat', dynamicQrEnabled: true, sources: { create: Object.entries(SOURCE_DEFAULTS).map(([sourceType, enabled]) => ({ providerCode: PROVIDER, sourceType, enabled })) } }, include: { sources: true } }); }
  private credentials(environment: string) { const prefix = environment === 'production' ? 'PAYCOOLS_PROD' : 'PAYCOOLS_UAT'; return { baseUrlConfigured: Boolean(this.env.get(`${prefix}_BASE_URL`)), appIdConfigured: Boolean(this.env.get(`${prefix}_APP_ID`)), appNameConfigured: Boolean(this.env.get(`${prefix}_APP_NAME`)), privateKeyConfigured: Boolean(this.env.get(`${prefix}_PRIVATE_KEY_BASE64`)), callbackSecretConfigured: Boolean(this.env.get(`${prefix}_CALLBACK_SECRET`)) }; }
  private ipWhitelistRequired(environment: string) { const prefix = environment === 'production' ? 'PAYCOOLS_PROD' : 'PAYCOOLS_UAT'; return this.env.get<string>(`${prefix}_IP_WHITELIST_REQUIRED`) === 'true'; }
  private callbackUrls() { const base = (this.env.get<string>('PUBLIC_API_URL') || 'https://api.wekonnek.biz').replace(/\/$/, ''); return { payment: `${base}/api/payments/callbacks/paycools/payment` }; }
  private confirmations(config: any, environment: Environment) { const prefix = environment === 'production' ? 'prod' : 'uat'; return { publicKeyRegistrationConfirmed: Boolean(config[`${prefix}PublicKeyRegistrationConfirmed`]), ipWhitelistConfirmed: Boolean(config[`${prefix}IpWhitelistConfirmed`]), callbackRegistrationConfirmed: Boolean(config[`${prefix}CallbackRegistrationConfirmed`]) }; }
  private connection(config: any, environment: Environment, credentials = this.credentials(environment)) { const prefix = environment === 'production' ? 'prod' : 'uat'; const testAt = config[`${prefix}LastConnectionTestAt`]; const successful = config[`${prefix}LastConnectionTestSuccessful`]; const errorCode = config[`${prefix}LastConnectionTestErrorCode`]; const status = !Object.values(credentials).every(Boolean) ? 'NOT_CONFIGURED' : successful === true ? 'HEALTHY' : testAt && successful === false ? 'ERROR' : 'READY_TO_TEST'; return { status, lastConnectionTestAt: testAt, lastConnectionTestSuccessful: successful, lastConnectionTestErrorCode: errorCode }; }
  private readiness(config: any, environment: Environment) { const credentials = this.credentials(environment); const configurationComplete = Object.values(credentials).every(Boolean); const confirmations = this.confirmations(config, environment); const connection = this.connection(config, environment, credentials); const ipWhitelistRequired = this.ipWhitelistRequired(environment); const missing = [...(!credentials.baseUrlConfigured ? ['BASE_URL'] : []), ...(!credentials.appIdConfigured ? ['APP_ID'] : []), ...(!credentials.appNameConfigured ? ['APP_NAME'] : []), ...(!credentials.privateKeyConfigured ? ['PRIVATE_KEY'] : []), ...(!credentials.callbackSecretConfigured ? ['CALLBACK_SECRET'] : []), ...(!confirmations.publicKeyRegistrationConfirmed ? ['PUBLIC_KEY_REGISTRATION'] : []), ...(!confirmations.callbackRegistrationConfirmed ? ['CALLBACK_REGISTRATION'] : []), ...(ipWhitelistRequired && !confirmations.ipWhitelistConfirmed ? ['IP_WHITELIST'] : []), ...(connection.status !== 'HEALTHY' ? ['CONNECTION_TEST'] : []), ...(!config.dynamicQrEnabled ? ['DYNAMIC_QR'] : [])]; const ready = missing.length === 0; return { credentials, configurationComplete, confirmations, connection, ipWhitelistRequired, missing, ready, uatStatus: !configurationComplete ? 'NOT_READY' : ready ? (config.enabled ? 'ACTIVE' : 'READY') : 'READY_FOR_TESTING', operationallyActive: Boolean(config.enabled && ready) }; }
  private checklist(config: any, readiness: any) { const types = new Set((config.events || []).filter((e: any) => e.success).map((e: any) => e.type)); const { credentials, confirmations, connection } = readiness; return [['UAT Base URL', credentials.baseUrlConfigured, true], ['App ID', credentials.appIdConfigured, true], ['Application Name', credentials.appNameConfigured, true], ['Private Key Installed', credentials.privateKeyConfigured, true], ['Public Key Registered', confirmations.publicKeyRegistrationConfirmed, false], ['Callback Secret', credentials.callbackSecretConfigured, true], ['Callback URL Registered', confirmations.callbackRegistrationConfirmed, false], ['IP Whitelist Confirmed', !readiness.ipWhitelistRequired || confirmations.ipWhitelistConfirmed, false], ['Connection Test', connection.status === 'HEALTHY', true], ['Dynamic QR Enabled', Boolean(config.dynamicQrEnabled), true], ['Test QR Generated', types.has('UAT_QR_CREATED'), true], ['Test Payment Received', types.has('UAT_PAYMENT_COMPLETED'), true], ['Callback Verified', types.has('CALLBACK_VERIFIED'), true], ['Order Marked Paid', types.has('ORDER_MARKED_PAID'), true]].map(([label, complete, automatic]) => ({ label, complete, automatic })); }

  paymentCallbackUrl() {
    return this.callbackUrls().payment;
  }

  /** Runtime PayCools credentials. Never expose this object from admin GET. */
  async getPayCoolsRuntime() {
    const config = await this.ensureConfig();
    const environment = (config.environment === 'production' ? 'production' : 'uat') as Environment;
    const prefix = environment === 'production' ? 'PAYCOOLS_PROD' : 'PAYCOOLS_UAT';
    return {
      environment,
      defaultQrExpirySeconds: config.defaultQrExpirySeconds,
      baseUrl: (this.env.get<string>(`${prefix}_BASE_URL`) || '').replace(/\/$/, ''),
      appId: this.env.get<string>(`${prefix}_APP_ID`) || '',
      privateKeyBase64: this.env.get<string>(`${prefix}_PRIVATE_KEY_BASE64`) || '',
      appName: this.env.get<string>(`${prefix}_APP_NAME`) || '',
      callbackSecret: this.env.get<string>(`${prefix}_CALLBACK_SECRET`) || '',
      channelCode: this.env.get<string>(`${prefix}_CHANNEL_CODE`) || 'QRPH_DYNAMIC_QR',
      notifyUrl: this.callbackUrls().payment,
    };
  }

  async get() { const config = await this.ensureConfig(); const events = await this.prisma.paymentPartnerEvent.findMany({ where: { configurationId: config.id }, orderBy: { createdAt: 'desc' }, take: 20 }); const expanded = { ...config, events }; const readiness = this.readiness(expanded, config.environment as Environment); return { ...config, credentials: readiness.credentials, configurationComplete: readiness.configurationComplete, confirmations: readiness.confirmations, connection: readiness.connection, readiness: { missing: readiness.missing, ready: readiness.ready, uatStatus: readiness.uatStatus, operationallyActive: readiness.operationallyActive, ipWhitelistRequired: readiness.ipWhitelistRequired }, callbackUrls: this.callbackUrls(), checklist: this.checklist(expanded, readiness), events }; }
  async getActiveProvider(sourceType: string) { const config = await this.ensureConfig(); const source = config.sources.find((entry) => entry.sourceType === sourceType); const readiness = this.readiness(config, config.environment as Environment); if (!readiness.operationallyActive || !config.dynamicQrEnabled || !source?.enabled) throw new BadRequestException('This payment method is currently unavailable'); return { providerCode: config.providerCode, environment: config.environment, defaultQrExpirySeconds: config.defaultQrExpirySeconds }; }

  async update(body: Record<string, unknown>, actor: { id: string }, context: { ip?: string; userAgent?: string }) {
    const current = await this.ensureConfig(); const data: Record<string, unknown> = {}; for (const field of MUTABLE_FIELDS) if (body[field] !== undefined) data[field] = body[field];
    if (data.environment && !['uat', 'production'].includes(String(data.environment))) throw new BadRequestException('Environment must be uat or production');
    if (data.defaultQrExpirySeconds !== undefined && (!Number.isInteger(data.defaultQrExpirySeconds) || Number(data.defaultQrExpirySeconds) < 300 || Number(data.defaultQrExpirySeconds) > 3600)) throw new BadRequestException('QR expiry must be between 300 and 3600 seconds');
    if (data.settlementMode && data.settlementMode !== 'MANUAL') throw new BadRequestException('Only manual settlement is supported'); if (data.refundEnabled === true) throw new BadRequestException('PayCools refunds are not implemented and remain disabled until refund UAT passes'); if (data.payoutEnabled === true) throw new BadRequestException('PayCools payouts are not part of this configuration and remain disabled');
    const targetEnvironment = (data.environment || current.environment) as Environment; if (targetEnvironment !== current.environment) data.enabled = false;
    const readiness = this.readiness({ ...current, ...data }, targetEnvironment); if (data.enabled === true && !readiness.ready) throw new BadRequestException({ code: 'PAYCOOLS_NOT_READY', message: 'PayCools cannot be enabled because UAT configuration is incomplete.', missing: readiness.missing });
    const highRisk = (data.environment === 'production' && current.environment !== 'production') || (current.environment === 'production' && current.enabled && data.enabled === false); if (highRisk && body.confirmation !== 'CONFIRM PAYCOOLS CHANGE') throw new BadRequestException('Elevated confirmation is required for this change');
    const sourceUpdates: Array<[string, unknown]> = body.sources && typeof body.sources === 'object' ? Object.entries(body.sources as Record<string, unknown>) : []; const changedEntries: Array<[string, unknown]> = [...Object.entries(data), ...sourceUpdates.map(([key, value]): [string, unknown] => [`source:${key}`, value])]; if (!changedEntries.length) throw new BadRequestException('No supported settings supplied');
    const changes = changedEntries.map(([field, value]) => ({ field, oldValue: field.startsWith('source:') ? current.sources.find((s) => s.sourceType === field.slice(7))?.enabled : (current as Record<string, unknown>)[field], newValue: value }));
    await this.prisma.$transaction(async (tx) => { await tx.paymentPartnerConfiguration.update({ where: { id: current.id }, data }); for (const [sourceType, enabled] of sourceUpdates) { if (!(sourceType in SOURCE_DEFAULTS) || typeof enabled !== 'boolean') throw new BadRequestException(`Unsupported source ${sourceType}`); await tx.paymentPartnerSourceConfig.upsert({ where: { providerCode_sourceType: { providerCode: PROVIDER, sourceType } }, update: { enabled }, create: { configurationId: current.id, providerCode: PROVIDER, sourceType, enabled } }); } await tx.paymentPartnerAuditLog.create({ data: { configurationId: current.id, actorId: actor.id, action: 'PAYCOOLS_CONFIGURATION_UPDATED', changes: changes as Prisma.InputJsonValue, ipAddress: context.ip, userAgent: context.userAgent } }); for (const [field, value] of Object.entries(data)) if (field.includes('Confirmed')) await tx.paymentPartnerEvent.create({ data: { configurationId: current.id, type: field.toUpperCase(), message: `${field.replace(/([A-Z])/g, ' $1').trim()} ${value ? 'confirmed' : 'unconfirmed'}`, success: Boolean(value), reference: actor.id } }); if (data.enabled !== undefined) await tx.paymentPartnerEvent.create({ data: { configurationId: current.id, type: data.enabled ? 'PAYCOOLS_ENABLED' : 'PAYCOOLS_DISABLED', message: `PayCools ${data.enabled ? 'enabled' : 'disabled'}`, success: true, reference: actor.id } }); });
    return this.get();
  }

  async testConnection(actorId: string) { const config = await this.ensureConfig(); const environment = config.environment as Environment; const credentials = this.credentials(environment); if (!Object.values(credentials).every(Boolean)) throw new BadRequestException({ code: 'PAYCOOLS_NOT_CONFIGURED', message: 'Complete UAT credentials before testing the connection.' }); const prefix = environment === 'production' ? 'PAYCOOLS_PROD' : 'PAYCOOLS_UAT'; const endpoint = this.env.get<string>(`${prefix}_HEALTHCHECK_URL`); if (!endpoint) throw new NotImplementedException('A documented PayCools health-check endpoint must be configured before connection testing is available'); const field = environment === 'production' ? 'prod' : 'uat'; try { const response = await fetch(endpoint, { method: 'GET', signal: AbortSignal.timeout(10_000) }); if (!response.ok) throw new Error(response.status === 401 || response.status === 403 ? 'AUTHENTICATION_REJECTED' : response.status === 408 ? 'TIMEOUT' : 'PROVIDER_UNAVAILABLE'); const now = new Date(); await this.prisma.paymentPartnerConfiguration.update({ where: { id: config.id }, data: { [`${field}LastConnectionTestAt`]: now, [`${field}LastConnectionTestSuccessful`]: true, [`${field}LastConnectionTestErrorCode`]: null, lastSuccessfulRequestAt: now } }); await this.prisma.paymentPartnerEvent.create({ data: { configurationId: config.id, type: 'CONNECTION_TEST_SUCCESSFUL', message: 'PayCools UAT connection test successful', success: true, reference: actorId } }); return this.get(); } catch (error) { const code = error instanceof Error && ['AUTHENTICATION_REJECTED', 'TIMEOUT', 'PROVIDER_UNAVAILABLE'].includes(error.message) ? error.message : 'PROVIDER_UNAVAILABLE'; await this.prisma.paymentPartnerConfiguration.update({ where: { id: config.id }, data: { [`${field}LastConnectionTestAt`]: new Date(), [`${field}LastConnectionTestSuccessful`]: false, [`${field}LastConnectionTestErrorCode`]: code } }); await this.prisma.paymentPartnerEvent.create({ data: { configurationId: config.id, type: 'CONNECTION_TEST_FAILED', message: `PayCools connection test failed: ${code.replaceAll('_', ' ').toLowerCase()}`, success: false, reference: actorId } }); throw new BadRequestException(`Connection test failed: ${code.replaceAll('_', ' ').toLowerCase()}`); } }
  reconcile() { throw new NotImplementedException('PayCools reconciliation API specifications are required before reconciliation can run'); }
}
