'use client';
import { ChangeEvent, FormEvent, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Camera, Images, MapPin, X } from 'lucide-react';
import { getToken } from '@/hooks/use-auth';
import { propertyApi, type PropertyType } from '@/lib/property';

type Photo={file:File;url:string};
export default function PostPropertyPage(){const router=useRouter(),gallery=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null);const [types,setTypes]=useState<PropertyType[]>([]),[photos,setPhotos]=useState<Photo[]>([]),[step,setStep]=useState(1),[transactionType,setTransactionType]=useState<'FOR_SALE'|'FOR_RENT'|''>(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(!getToken()){router.replace('/auth/login?redirect=%2Fproperty%2Fpost');return;}propertyApi.types().then(setTypes).catch(e=>setError(e.message));},[router]);
  const add=(e:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(e.target.files||[]).slice(0,20-photos.length);setPhotos(p=>[...p,...files.map(file=>({file,url:URL.createObjectURL(file)}))]);e.target.value='';};
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!photos.length){setError('Add at least one property photo.');setStep(5);return;}setBusy(true);setError('');try{const form=new FormData(e.currentTarget),upload=new FormData();photos.forEach(p=>upload.append('files',p.file));upload.append('type','property');const up=await fetch('/api/backend/upload/multiple',{method:'POST',headers:{Authorization:`Bearer ${getToken()}`},body:upload});const upBody=await up.json() as {message?:string;urls?:string[]};if(!up.ok||!upBody.urls)throw new Error(upBody.message||'Photo upload failed');const body:Record<string,unknown>=Object.fromEntries(form);for(const key of ['price','bedrooms','bathrooms','parkingSpaces','floorArea','lotArea','latitude','longitude'])if(body[key]==='')delete body[key];body.showExactLocation=form.get('showExactLocation')==='on';body.imageUrls=upBody.urls;const draft=await propertyApi.create(body);await propertyApi.publish(draft.id,Number(form.get('durationDays'))||30);router.push(`/property/${draft.slug}`);}catch(err){setError(err instanceof Error?err.message:'Unable to publish property');}finally{setBusy(false);}};
  return <div className="mx-auto max-w-3xl px-4 py-8"><Link href="/property" className="text-sm font-bold text-slate-600">← Back to Property</Link><h1 className="mt-4 text-3xl font-black">Post a Property</h1><p className="text-slate-500">Create a visual, searchable property listing.</p><div className="mt-6 flex gap-1">{['Transaction','Type & details','Location','Seller','Photos','Review'].map((label,i)=><button key={label} onClick={()=>setStep(i+1)} className={`min-w-0 flex-1 border-b-4 px-1 py-2 text-[10px] font-bold sm:text-xs ${step===i+1?'border-red-600 text-red-700':'border-slate-200 text-slate-400'}`}>{i+1}. {label}</button>)}</div>
    <form onSubmit={submit} className="mt-5 rounded-2xl border bg-white p-5 shadow-sm sm:p-7">
      <section className={step===1?'':'hidden'}><h2 className="text-xl font-black">Is the property for sale or rent?</h2><div className="mt-5 grid grid-cols-2 gap-3"><label className="cursor-pointer rounded-xl border p-5 text-center font-black has-[:checked]:border-red-600 has-[:checked]:bg-red-50"><input required type="radio" name="transactionType" value="FOR_SALE" checked={transactionType==='FOR_SALE'} onChange={()=>setTransactionType('FOR_SALE')} className="sr-only"/>For Sale</label><label className="cursor-pointer rounded-xl border p-5 text-center font-black has-[:checked]:border-blue-600 has-[:checked]:bg-blue-50"><input required type="radio" name="transactionType" value="FOR_RENT" checked={transactionType==='FOR_RENT'} onChange={()=>setTransactionType('FOR_RENT')} className="sr-only"/>For Rent</label></div><label className={`mt-5 block text-sm font-bold transition-opacity ${transactionType==='FOR_SALE'?'opacity-45':''}`}>Rent price period<select name="pricePeriod" defaultValue="MONTHLY" disabled={transactionType!=='FOR_RENT'} aria-disabled={transactionType!=='FOR_RENT'} className="mt-2 w-full rounded-xl border bg-white p-3 font-normal disabled:cursor-not-allowed disabled:bg-slate-100"><option>MONTHLY</option><option>DAILY</option><option>YEARLY</option></select>{transactionType==='FOR_SALE'&&<span className="mt-1 block text-xs font-normal">Not applicable to properties for sale.</span>}</label></section>
      <section className={step===2?'grid gap-4':'hidden'}><h2 className="text-xl font-black">Property details</h2><label className="text-sm font-bold">Property type<select name="propertyTypeId" required defaultValue="" className="mt-1 w-full rounded-xl border bg-white p-3 font-normal"><option value="" disabled>Select property type</option>{types.map(t=><option key={t.id} value={t.id}>{t.groupName} — {t.name}</option>)}</select></label><label className="text-sm font-bold">Listing title<input name="title" required minLength={5} placeholder="e.g. Bright 2BR condominium near BGC" className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><label className="text-sm font-bold">Description<textarea name="description" required minLength={20} rows={5} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><label className="text-sm font-bold">Price (₱)<input name="price" required type="number" min="0" step="0.01" className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[['bedrooms','Bedrooms'],['bathrooms','Bathrooms'],['parkingSpaces','Parking'],['floorArea','Floor area sqm'],['lotArea','Lot area sqm']].map(([name,label])=><label key={name} className="text-xs font-bold">{label}<input name={name} type="number" min="0" step={name==='bathrooms'?'0.5':'1'} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label>)}</div><label className="text-sm font-bold">Furnished status<select name="furnishedStatus" className="mt-1 w-full rounded-xl border bg-white p-3 font-normal"><option value="">Not specified</option><option>Unfurnished</option><option>Semi-furnished</option><option>Fully furnished</option></select></label></section>
      <section className={step===3?'grid gap-4':'hidden'}><h2 className="flex items-center gap-2 text-xl font-black"><MapPin/>Location</h2><input name="addressLine" placeholder="Street / building (kept private by default)" className="rounded-xl border p-3"/><input name="barangay" placeholder="Barangay" className="rounded-xl border p-3"/><div className="grid grid-cols-2 gap-3"><input name="city" required placeholder="City / municipality" className="rounded-xl border p-3"/><input name="province" required placeholder="Province" className="rounded-xl border p-3"/></div><div className="grid grid-cols-2 gap-3"><input name="latitude" type="number" step="any" placeholder="Latitude" className="rounded-xl border p-3"/><input name="longitude" type="number" step="any" placeholder="Longitude" className="rounded-xl border p-3"/></div><button type="button" onClick={()=>navigator.geolocation?.getCurrentPosition(p=>{const form=document.querySelector('form') as HTMLFormElement;(form.elements.namedItem('latitude') as HTMLInputElement).value=String(p.coords.latitude);(form.elements.namedItem('longitude') as HTMLInputElement).value=String(p.coords.longitude);})} className="rounded-xl border py-3 font-bold text-blue-700">Use my current location</button><label className="flex items-center gap-2 text-sm"><input name="showExactLocation" type="checkbox"/>Allow exact map pin to be public</label></section>
      <section className={step===4?'grid gap-4':'hidden'}><h2 className="text-xl font-black">Who is posting?</h2><select name="sellerType" className="rounded-xl border bg-white p-3"><option value="OWNER">Property Owner</option><option value="BROKER">Broker / Agent</option><option value="DEVELOPER">Developer</option></select><input name="agencyName" placeholder="Agency or developer company (optional)" className="rounded-xl border p-3"/><input name="prcLicenseNumber" placeholder="PRC license number (brokers, optional)" className="rounded-xl border p-3"/><input name="contactName" placeholder="Public contact name" className="rounded-xl border p-3"/><p className="text-xs text-slate-500">Phone and email remain private; inquiries are routed through WEKONNEK.</p></section>
      <section className={step===5?'':'hidden'}><h2 className="text-xl font-black">Property photos <span className="text-sm text-slate-500">({photos.length}/20)</span></h2><input ref={gallery} type="file" accept="image/jpeg,image/png" multiple onChange={add} className="sr-only"/><input ref={camera} type="file" accept="image/jpeg,image/png" capture="environment" onChange={add} className="sr-only"/><div className="mt-4 grid grid-cols-3 gap-3 sm:grid-cols-5">{photos.map((p,i)=><div key={p.url} className="relative aspect-square overflow-hidden rounded-xl"><img src={p.url} alt="" className="size-full object-cover"/><button type="button" onClick={()=>setPhotos(v=>v.filter(x=>x.url!==p.url))} className="absolute right-1 top-1 rounded-full bg-black/70 p-1 text-white"><X size={14}/></button>{i===0&&<span className="absolute bottom-1 left-1 rounded bg-white px-1 text-[9px] font-bold">COVER</span>}</div>)}</div><div className="mt-4 grid grid-cols-2 gap-3"><button type="button" onClick={()=>gallery.current?.click()} className="flex min-h-24 flex-col items-center justify-center rounded-xl border-2 border-dashed font-bold"><Images/>Gallery</button><button type="button" onClick={()=>camera.current?.click()} className="flex min-h-24 flex-col items-center justify-center rounded-xl border-2 border-dashed font-bold"><Camera/>Camera</button></div></section>
      <section className={step===6?'grid gap-4':'hidden'}><h2 className="text-xl font-black">Review and publish</h2><p className="rounded-xl bg-blue-50 p-4 text-sm">Your listing will be searchable by property type and location. WEKONNEK may suspend listings that violate property policies.</p><label className="text-sm font-bold">Listing duration<select name="durationDays" className="mt-1 w-full rounded-xl border bg-white p-3 font-normal"><option value="7">7 days</option><option value="15">15 days</option><option value="30">30 days</option></select></label><button disabled={busy} className="rounded-xl bg-[#DB0002] py-4 font-black text-white disabled:opacity-50">{busy?'Uploading and publishing…':'Publish Property'}</button></section>
      {error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<div className="mt-5 flex justify-between"><button type="button" disabled={step===1} onClick={()=>setStep(s=>Math.max(1,s-1))} className="rounded-xl border px-5 py-2.5 font-bold disabled:opacity-30">Back</button>{step<6&&<button type="button" onClick={()=>setStep(s=>Math.min(6,s+1))} className="rounded-xl bg-blue-700 px-6 py-2.5 font-black text-white">Continue</button>}</div>
    </form></div>;
}
