CREATE TYPE "PropertyTransactionType" AS ENUM ('FOR_SALE', 'FOR_RENT');
CREATE TYPE "PropertyPricePeriod" AS ENUM ('MONTHLY', 'DAILY', 'YEARLY', 'NONE');
CREATE TYPE "PropertyListingStatus" AS ENUM ('DRAFT', 'PENDING', 'ACTIVE', 'RESERVED', 'SOLD', 'RENTED', 'EXPIRED', 'INACTIVE', 'REJECTED', 'SUSPENDED');
CREATE TYPE "PropertySellerType" AS ENUM ('OWNER', 'BROKER', 'DEVELOPER');
CREATE TYPE "PropertyViewingStatus" AS ENUM ('PENDING', 'CONFIRMED', 'DECLINED', 'COMPLETED', 'CANCELLED');

CREATE TABLE "property_types" ("id" UUID NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "group_name" TEXT NOT NULL, "display_order" INTEGER NOT NULL DEFAULT 0, "is_active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "property_types_pkey" PRIMARY KEY ("id"));
CREATE TABLE "property_listing_plans" ("id" UUID NOT NULL, "name" TEXT NOT NULL, "duration_days" INTEGER NOT NULL, "listing_fee" DECIMAL(12,2) NOT NULL DEFAULT 0, "featured_days" INTEGER NOT NULL DEFAULT 0, "max_photos" INTEGER NOT NULL DEFAULT 20, "active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "property_listing_plans_pkey" PRIMARY KEY ("id"));
CREATE TABLE "property_listings" ("id" UUID NOT NULL, "owner_id" UUID NOT NULL, "property_type_id" UUID NOT NULL, "plan_id" UUID, "title" TEXT NOT NULL, "slug" TEXT NOT NULL, "description" TEXT NOT NULL, "transaction_type" "PropertyTransactionType" NOT NULL, "price" DECIMAL(14,2) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'PHP', "price_period" "PropertyPricePeriod" NOT NULL DEFAULT 'NONE', "bedrooms" INTEGER, "bathrooms" DECIMAL(4,1), "parking_spaces" INTEGER, "floor_area" DECIMAL(12,2), "lot_area" DECIMAL(12,2), "furnished_status" TEXT, "address_line" TEXT, "barangay" TEXT, "city" TEXT NOT NULL, "province" TEXT NOT NULL, "postal_code" TEXT, "latitude" DECIMAL(10,7), "longitude" DECIMAL(10,7), "show_exact_location" BOOLEAN NOT NULL DEFAULT false, "contact_name" TEXT, "contact_phone" TEXT, "contact_email" TEXT, "seller_type" "PropertySellerType" NOT NULL DEFAULT 'OWNER', "agency_name" TEXT, "prc_license_number" TEXT, "is_verified" BOOLEAN NOT NULL DEFAULT false, "is_featured" BOOLEAN NOT NULL DEFAULT false, "featured_until" TIMESTAMP(3), "listing_status" "PropertyListingStatus" NOT NULL DEFAULT 'DRAFT', "status_before_suspend" "PropertyListingStatus", "moderation_reason" TEXT, "available_from" DATE, "published_at" TIMESTAMP(3), "expires_at" TIMESTAMP(3), "view_count" INTEGER NOT NULL DEFAULT 0, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "property_listings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "property_images" ("id" UUID NOT NULL, "property_listing_id" UUID NOT NULL, "image_url" TEXT NOT NULL, "sort_order" INTEGER NOT NULL DEFAULT 0, "is_primary" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "property_images_pkey" PRIMARY KEY ("id"));
CREATE TABLE "saved_properties" ("id" UUID NOT NULL, "user_id" UUID NOT NULL, "property_listing_id" UUID NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "saved_properties_pkey" PRIMARY KEY ("id"));
CREATE TABLE "property_viewing_requests" ("id" UUID NOT NULL, "property_listing_id" UUID NOT NULL, "requester_id" UUID NOT NULL, "preferred_date" DATE NOT NULL, "preferred_time" TEXT NOT NULL, "name" TEXT NOT NULL, "contact_number" TEXT NOT NULL, "message" TEXT, "status" "PropertyViewingStatus" NOT NULL DEFAULT 'PENDING', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "property_viewing_requests_pkey" PRIMARY KEY ("id"));
CREATE TABLE "property_reports" ("id" UUID NOT NULL, "property_listing_id" UUID NOT NULL, "reporter_id" UUID NOT NULL, "reason" TEXT NOT NULL, "details" TEXT, "status" TEXT NOT NULL DEFAULT 'OPEN', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "property_reports_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "property_types_slug_key" ON "property_types"("slug");
CREATE INDEX "property_types_group_name_is_active_display_order_idx" ON "property_types"("group_name", "is_active", "display_order");
CREATE UNIQUE INDEX "property_listings_slug_key" ON "property_listings"("slug");
CREATE INDEX "property_listings_transaction_type_listing_status_idx" ON "property_listings"("transaction_type", "listing_status");
CREATE INDEX "property_listings_property_type_id_listing_status_idx" ON "property_listings"("property_type_id", "listing_status");
CREATE INDEX "property_listings_city_barangay_idx" ON "property_listings"("city", "barangay");
CREATE INDEX "property_listings_price_idx" ON "property_listings"("price");
CREATE INDEX "property_listings_latitude_longitude_idx" ON "property_listings"("latitude", "longitude");
CREATE INDEX "property_listings_listing_status_is_featured_created_at_idx" ON "property_listings"("listing_status", "is_featured", "created_at");
CREATE INDEX "property_listings_owner_id_listing_status_idx" ON "property_listings"("owner_id", "listing_status");
CREATE INDEX "property_images_property_listing_id_sort_order_idx" ON "property_images"("property_listing_id", "sort_order");
CREATE UNIQUE INDEX "saved_properties_user_id_property_listing_id_key" ON "saved_properties"("user_id", "property_listing_id");
CREATE INDEX "saved_properties_user_id_created_at_idx" ON "saved_properties"("user_id", "created_at");
CREATE INDEX "property_viewing_requests_property_listing_id_status_idx" ON "property_viewing_requests"("property_listing_id", "status");
CREATE INDEX "property_viewing_requests_requester_id_created_at_idx" ON "property_viewing_requests"("requester_id", "created_at");
CREATE UNIQUE INDEX "property_reports_reporter_id_property_listing_id_key" ON "property_reports"("reporter_id", "property_listing_id");
CREATE INDEX "property_reports_status_created_at_idx" ON "property_reports"("status", "created_at");

ALTER TABLE "property_listings" ADD CONSTRAINT "property_listings_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "property_listings" ADD CONSTRAINT "property_listings_property_type_id_fkey" FOREIGN KEY ("property_type_id") REFERENCES "property_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "property_listings" ADD CONSTRAINT "property_listings_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "property_listing_plans"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "property_images" ADD CONSTRAINT "property_images_property_listing_id_fkey" FOREIGN KEY ("property_listing_id") REFERENCES "property_listings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "saved_properties" ADD CONSTRAINT "saved_properties_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "saved_properties" ADD CONSTRAINT "saved_properties_property_listing_id_fkey" FOREIGN KEY ("property_listing_id") REFERENCES "property_listings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "property_viewing_requests" ADD CONSTRAINT "property_viewing_requests_property_listing_id_fkey" FOREIGN KEY ("property_listing_id") REFERENCES "property_listings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "property_viewing_requests" ADD CONSTRAINT "property_viewing_requests_requester_id_fkey" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "property_reports" ADD CONSTRAINT "property_reports_property_listing_id_fkey" FOREIGN KEY ("property_listing_id") REFERENCES "property_listings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "property_reports" ADD CONSTRAINT "property_reports_reporter_id_fkey" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO "property_types" ("id", "name", "slug", "group_name", "display_order", "updated_at") VALUES
('10000000-0000-4000-8000-000000000001','Condominium','condominium','Residential',1,NOW()),('10000000-0000-4000-8000-000000000002','House & Lot','house-and-lot','Residential',2,NOW()),('10000000-0000-4000-8000-000000000003','Apartment','apartment','Residential',3,NOW()),('10000000-0000-4000-8000-000000000004','Townhouse','townhouse','Residential',4,NOW()),('10000000-0000-4000-8000-000000000005','Residential Lot','residential-lot','Residential',5,NOW()),('10000000-0000-4000-8000-000000000006','Room / Bedspace','room-bedspace','Residential',6,NOW()),('10000000-0000-4000-8000-000000000007','Vacation Property','vacation-property','Residential',7,NOW()),
('10000000-0000-4000-8000-000000000008','Commercial Space','commercial-space','Commercial',1,NOW()),('10000000-0000-4000-8000-000000000009','Retail Space','retail-space','Commercial',2,NOW()),('10000000-0000-4000-8000-000000000010','Office Space','office-space','Commercial',3,NOW()),('10000000-0000-4000-8000-000000000011','Warehouse / Industrial Property','warehouse-industrial','Commercial',4,NOW()),('10000000-0000-4000-8000-000000000012','Building','building','Commercial',5,NOW()),('10000000-0000-4000-8000-000000000013','Commercial Lot','commercial-lot','Commercial',6,NOW()),
('10000000-0000-4000-8000-000000000014','Residential Land','residential-land','Land',1,NOW()),('10000000-0000-4000-8000-000000000015','Commercial Land','commercial-land','Land',2,NOW()),('10000000-0000-4000-8000-000000000016','Agricultural / Farm Land','agricultural-farm-land','Land',3,NOW()),
('10000000-0000-4000-8000-000000000017','Pre-selling','pre-selling','Development',1,NOW()),('10000000-0000-4000-8000-000000000018','New Development','new-development','Development',2,NOW());
INSERT INTO "property_listing_plans" ("id","name","duration_days","listing_fee","max_photos","updated_at") VALUES ('20000000-0000-4000-8000-000000000007','7 Days',7,0,20,NOW()),('20000000-0000-4000-8000-000000000015','15 Days',15,0,20,NOW()),('20000000-0000-4000-8000-000000000030','30 Days',30,0,20,NOW());
